-- CRIA BANCO DE DADOS
CREATE DATABASE finances WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

\c finances;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER DATABASE finances SET "TimeZone" TO "America/Sao_Paulo";

CREATE TABLE CATEGORY(
    ID BIGINT not null,
    ABBREVIATION CHARACTER VARYING(20) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (ID),
    CONSTRAINT CATEGORY_UNQ UNIQUE (ABBREVIATION)
);

CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQ AS BIGINT INCREMENT BY 1 START WITH 1 CACHE 1;


--
INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'ALIMENTACAO', 'Alimentação');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'EDUCACAO', 'Educação');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'LAZER', 'Lazer');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'MORADIA', 'Moradia');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'SAUDE', 'Saúde');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION)
VALUES (nextval('CATEGORY_SEQ'), 'TRANSPORTE', 'Transporte');