-- CRIA BANCO DE DADOS
CREATE DATABASE finances WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

\c finances;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER DATABASE finances SET "TimeZone" TO "America/Sao_Paulo";

CREATE TABLE CATEGORY(
    ID BIGINT not null,
    ABBREVIATION CHARACTER VARYING(20) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    TYPE CHARACTER VARYING(10) NOT NULL,
    BUDGET NUMERIC(10,2) NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (ID),
    CONSTRAINT CATEGORY_UNQ UNIQUE (ABBREVIATION)
);

CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQ AS BIGINT INCREMENT BY 1 START WITH 1 CACHE 1;

CREATE TABLE INCOME(
    ID BIGINT not null,
    AMOUNT NUMERIC(10,2) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT INCOME_PK PRIMARY KEY (ID),
    CONSTRAINT INCOME_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE SEQUENCE IF NOT EXISTS INCOME_SEQ AS BIGINT INCREMENT BY 1 START WITH 1 CACHE 1;

CREATE TABLE EXPENSE(
    ID BIGINT not null,
    AMOUNT NUMERIC(10,2) NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT EXPENSE_PK PRIMARY KEY (ID),
    CONSTRAINT EXPENSE_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE SEQUENCE IF NOT EXISTS EXPENSE_SEQ AS BIGINT INCREMENT BY 1 START WITH 1 CACHE 1;

--
INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'ALIMENTACAO', 'Alimentação', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'EDUCACAO', 'Educação', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'LAZER', 'Lazer', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'MORADIA', 'Moradia', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'SAUDE', 'Saúde', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'TRANSPORTE', 'Transporte', 'EXPENSE');

INSERT INTO CATEGORY (ID, ABBREVIATION, DESCRIPTION, TYPE)
VALUES (nextval('CATEGORY_SEQ'), 'SALARIO', 'Salário', 'INCOME');